config/routes.rb
Rails.application.routes.draw do
  resources :rewards
  resources :reward_tiers
  resources :reward_types
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'welcome#index'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    get 'sign_up', to: 'devise/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
  end

  resources :invoices do
  end

end

app/controllers/reward_types_controller.rb
class RewardTypesController < ApplicationController
  before_action :set_reward_type, only: [:show, :edit, :update, :destroy]

  # GET /reward_types
  # GET /reward_types.json
  def index
    @reward_types = RewardType.all
  end

  # GET /reward_types/1
  # GET /reward_types/1.json
  def show
  end

  # GET /reward_types/new
  def new
    @reward_type = RewardType.new
  end

  # GET /reward_types/1/edit
  def edit
  end

  # POST /reward_types
  # POST /reward_types.json
  def create
    @reward_type = RewardType.new(reward_type_params)

    respond_to do |format|
      if @reward_type.save
        format.html { redirect_to @reward_type, notice: 'Reward type was successfully created.' }
        format.json { render :show, status: :created, location: @reward_type }
      else
        format.html { render :new }
        format.json { render json: @reward_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reward_types/1
  # PATCH/PUT /reward_types/1.json
  def update
    respond_to do |format|
      if @reward_type.update(reward_type_params)
        format.html { redirect_to @reward_type, notice: 'Reward type was successfully updated.' }
        format.json { render :show, status: :ok, location: @reward_type }
      else
        format.html { render :edit }
        format.json { render json: @reward_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reward_types/1
  # DELETE /reward_types/1.json
  def destroy
    @reward_type.destroy
    respond_to do |format|
      format.html { redirect_to reward_types_url, notice: 'Reward type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward_type
      @reward_type = RewardType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_type_params
      params.require(:reward_type).permit(:name, :description)
    end
end

app/helpers/reward_types_helper.rb
module RewardTypesHelper
end

app/views/reward_types/_form.html.erb
<%= form_for(@reward_type) do |f| %>
  <% if @reward_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward_type.errors.count, "error") %> prohibited this reward_type from being saved:</h2>

      <ul>
      <% @reward_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reward_types/edit.html.erb
<h1>Editing Reward Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward_type %> |
<%= link_to 'Back', reward_types_path %>

app/views/reward_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reward Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reward_types.each do |reward_type| %>
      <tr>
        <td><%= reward_type.name %></td>
        <td><%= reward_type.description %></td>
        <td><%= link_to 'Show', reward_type %></td>
        <td><%= link_to 'Edit', edit_reward_type_path(reward_type) %></td>
        <td><%= link_to 'Destroy', reward_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward type', new_reward_type_path %>

app/views/reward_types/new.html.erb
<h1>New Reward Type</h1>

<%= render 'form' %>

<%= link_to 'Back', reward_types_path %>

app/views/reward_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reward_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reward_type.description %>
</p>

<%= link_to 'Edit', edit_reward_type_path(@reward_type) %> |
<%= link_to 'Back', reward_types_path %>